language: node_js
sudo: false
node_js: '9'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g gitbook-cli
install:
  - gitbook install
  - gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: _book
  target_branch: gh-pages
  keep_history: false
  on:
    branch: master

